# Generated by Django 5.0 on 2024-11-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_publication_delete_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='h_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
