# Generated by Django 5.0 on 2024-12-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_author_author_id_author_h_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='address',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
