# Generated by Django 5.0 on 2024-12-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_author_address_remove_author_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='document_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='language',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='wos_id',
            field=models.TextField(unique=True),
        ),
    ]
