# Generated by Django 5.0 on 2024-12-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_publication_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='slug',
        ),
        migrations.AlterField(
            model_name='publication',
            name='wos_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
